#### Data Analysis
- sciene means study
- The complete study of data called as data science
- the meaningful information said to be data
- raw data contains some null values
- extraction of required data is called as data mining
- the analyis of data means user can able to understand the information behind the data
- we will pre-process the data
- data will be passed to machine 
- machine is leaning on the basis of data given using algorithms
- artificial intelligence
- data analysis,machine learning and aritificial intelligence altogether called as data science

##### Data Analysis
- analysing the data in a perticular process
- gathering/generating data samples
- arranging the data 
- go for analysis
    - Ex:your institute(Eng Clg)
    1. principal 
        3. Vice Principal
    2. HOD's
        - different departments
    3. Faculty
        - teaching and non-teaching
    4. Ground Level
        - sanitization workers
    5. Students
        - 2000
        
- personal information
    1. name :string
    2. contact address
        - combo of all
    3. mobile 
        - integer

#### library
    - :all depts(clusters)
        - books,magzines

##### Module
- collection/group of statements called as function(book)
- group of functions called as module(dept)
    - for each module there is some purpose
- group/collection of modules called as package(library)

In [2]:
import math
# used for mathematical operations

In [4]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [5]:
math.factorial(6)

720

In [6]:
help(math.factorial)

Help on built-in function factorial in module math:

factorial(x, /)
    Find x!.
    
    Raise a ValueError if x is negative or non-integral.



In [7]:
math.factorial(-1)

ValueError: factorial() not defined for negative values

In [8]:
math.factorial('5')

TypeError: an integer is required (got type str)

In [9]:
math.gcd(9,21) # 3

3

In [10]:
math.gcd(8,23) # 1 greatest common divisor

1

In [11]:
math.pi

3.141592653589793

In [12]:
math.pow(4,4)

256.0

In [13]:
help(math.pow)

Help on built-in function pow in module math:

pow(x, y, /)
    Return x**y (x to the power of y).



In [14]:
import random
# used to generate and deal with random in a given range

In [15]:
dir(random)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_BuiltinMethodType',
 '_MethodType',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_inst',
 '_itertools',
 '_log',
 '_os',
 '_pi',
 '_random',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [16]:
import re
# regular expression used for data validation

In [21]:
random.randint(9,45) # range

43

rolling a die:random values from 1 to 6

In [24]:
random.randint(10,40)

31

In [23]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



#### creating own modules
- create one package(directory)
    - create module
        - multiple functions

In [26]:
# some functions
def factorial(n):
    fact=1
    if n<0:
        return -1
    elif n==0:
        return 0
    else:
        for dig in range(1,n+1):
            fact*=dig
    return fact
factorial(5)

120

In [27]:
def is_prime(n):
    count=0
    if n==1:
        return 1
    else:
        for dig in range(1,n+1):
            if n%dig==0:
                count+=1
        if count==2:
            return True
        else:
            return False
is_prime(6)

False

In [28]:
is_prime(11)

True

In [29]:
def is_even(n):
    if n>0:
        if n%2==0:
            return True
        else:return False
    else:
        return -1
    
is_even(-8)

-1

In [30]:
def frequency(st,ch):
    return st.count(ch)

frequency('ruthu','u')

2

In [35]:
def is_palindrome(st):
    if len(st)==1:
        return -1
    else:
        if st==st[::-1]:
            return True
        else:
            return False
        
is_palindrome('121')

True

In [36]:
is_palindrome('mom')

True

In [40]:
def reverse(it):
    return reversed(it)

for val in reverse([5,6,79]):
    print(val)

79
6
5


In [42]:
for ch in reverse('ruthu'):
    print(ch)

u
h
t
u
r


In [43]:
import package

In [44]:
dir(package)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

In [46]:
from package import first

In [47]:
dir(first)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'factorial',
 'is_even',
 'is_prime']

In [49]:
from package import second

In [51]:
from package import info

In [53]:
from package import first,second,info

In [54]:
from package import first as f

In [56]:
from package import first,second as f

In [57]:
dir(f)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'frequency',
 'is_palindrome',
 'reverse',
 'val']

In [58]:
import sample

In [59]:
dir(sample)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'factorial',
 'is_even',
 'is_prime']

In [60]:
import sample as s

In [61]:
s.factorial(5)

120

In [62]:
help(s.factorial)

Help on function factorial in module sample:

factorial(n)
    # some functions



In [63]:
from package import info

In [64]:
dir(info)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']

In [65]:
help(info)

Help on module package.info in package:

NAME
    package.info

DESCRIPTION
    this file contains information about the modules we created
    first.py contains
    factorial
    is_prime
    is_even functions
    second.py file conatins
    some string methods and reversed function

FILE
    c:\users\lenovo\documents\da workshop\day4\package\info.py




In [66]:
s # path of s

<module 'sample' from 'C:\\Users\\lenovo\\Documents\\DA workshop\\Day4\\sample.py'>

In [67]:
s.is_prime(5)

True

In [73]:
from package import second as sec

In [74]:
sec.frequency('madam','a')

2

In [75]:
sec.frequency('college','e')

2

In [76]:
for val in sec.reverse(['hi',5,61,90]):
    print(val)

90
61
5
hi


#### Numpy
- Numpy stands for NumericaPython
- one of the most important data science modules
- used for scientific computation
- deal with array type of data

##### array()
- like matrix form
- n dimensional data
- we can create 32 dimensional array
- array is the homogenous data structure
- it is immutable
- numpy.array() that represents the array

In [80]:
import numpy as std

In [83]:
std.__version__

'1.18.1'

In [84]:
dir(std)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [85]:
# std.array(ele/data)

In [87]:
# convert string into array
# str considered as object
std.array('student')

array('student', dtype='<U7')

In [89]:
# create array with list of elements
import numpy as np
lit=[1,2,3,4,5] # comma separated val
li=np.array(lit)
print(li) # space separated

[1 2 3 4 5]


In [90]:
# diff b/w list and array
# list is mutable
# array is immutable
# list 1dimensional data
# array ndimensional(32)
# list is heterogenous data structure
# array is homogenous data structure

In [91]:
import numpy as vikas
A=vikas.array([[1,2,3],[5,6,7]]) # first list--forst row
print(A)


[[1 2 3]
 [5 6 7]]


In [94]:
# list of tuples
B=vikas.array([(1,2,3),(5,6,7,'a')]) # first list--forst row
print(B)
B.ndim # i dimensional

[(1, 2, 3) (5, 6, 7, 'a')]


1

In [100]:
ar=vikas.array([['a','b','c'],[1,2,3]])
print(ar)

[['a' 'b' 'c']
 ['1' '2' '3']]


In [102]:
a=np.array([1,2,3,4,5],dtype='float')
print(a)

[1. 2. 3. 4. 5.]


In [103]:
a.size # no.of values

5

In [107]:
A.shape # rows,col

(2, 3)

In [108]:
a.shape # 5 rows

(5,)

In [109]:
A.dtype

dtype('int32')

In [110]:
A.itemsize # int:4 bytes

4

In [112]:
A.ndim # no.of dimensions

2

In [114]:
# while creating the array we can add --> ndim
new=np.array([9,5,6,8],ndmin=4)
new

array([[[[9, 5, 6, 8]]]])

In [115]:
# while creating the array we can add --> ndim
new=np.array([9,5,6,8],ndmin=32)
new

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[9, 5,
                                      6, 8]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [126]:
n=np.array([[[1,2,3],[3,4,5]],[[9,4,5,],[5,3,1]],
             [[9,4,5],[2,1,0]]])
print(n) # each sub array is 2x3 shape

[[[1 2 3]
  [3 4 5]]

 [[9 4 5]
  [5 3 1]]

 [[9 4 5]
  [2 1 0]]]


In [125]:
n.ndim

3

In [ ]:
# creating array with set and dict

In [131]:
A={3,4,5,10,90,34,19,34,10,9}
SA=np.array(A)
print(SA)

{34, 3, 4, 5, 9, 10, 19, 90}


In [133]:
# using dict
dic={1:'h',2:'hey','name':'vikas','from':'GVPCE',
    'trainer':'vanitha'}
print(np.array(dic))

{1: 'h', 2: 'hey', 'name': 'vikas', 'from': 'GVPCE', 'trainer': 'vanitha'}
