#### Today Topics
- contiues with Numpy

##### sub modules of numpy
- arange()
- eye()
- ones()
- zeros()
- full()
- fill()
- linspace()
- reshape()
- random()

In [1]:
# arange()

In [2]:
import numpy as np

In [4]:
ar=np.arange(12) # similar to range()
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
ar2=np.arange(20,50) # arange(start,stop)
print(ar2)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [7]:
ar3=np.arange(20,50,6) # 6 diff
print(ar3)

[20 26 32 38 44]


In [8]:
#try by yourself

In [9]:
ar2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
len(ar2)

30

In [12]:
#30-->(1,30),(2,15),(3,10),(5,6) and vice-versa
ar2.reshape(3,10) # 3 rows and 10 cols

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
ar2.reshape(5,6)

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [15]:
# while reshaping the values
ar2.reshape(6,-1) # 30:6x5

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [18]:
ar2.reshape(-5,10) # unknown value represented by -values
# 10 cols in each row

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [19]:
# identity array
i=np.eye(4) # single value
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
print(np.eye(2,3)) # 2,3

[[1. 0. 0.]
 [0. 1. 0.]]


In [21]:
o=np.ones(3) # single val-->1d array
print(o)

[1. 1. 1.]


In [25]:
print(np.ones((2,3),dtype='int')) # shape

[[1 1 1]
 [1 1 1]]


In [28]:
z=np.zeros((4)) # 1d array
print(z)

[0. 0. 0. 0.]


In [29]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


full and fill

In [30]:
fl=np.full((3),4) # shape,ele
print(fl)

[4 4 4]


In [31]:
f=np.full((4,4),2)
print(f)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [32]:
# fill with specified one
f.fill(9)

In [33]:
f

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [37]:
f.fill('h') # it accepts only integer

ValueError: invalid literal for int() with base 10: 'h'

In [36]:
f

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [39]:
# diag()
new=ar2.reshape(5,6)
print(new)

[[20 21 22 23 24 25]
 [26 27 28 29 30 31]
 [32 33 34 35 36 37]
 [38 39 40 41 42 43]
 [44 45 46 47 48 49]]


In [40]:
print(np.diag(new)) # you will get the diagonal values

[20 27 34 41 48]


In [41]:
dg=np.diag([4,5,'h',9,1])
print(dg)

[['4' '' '' '' '']
 ['' '5' '' '' '']
 ['' '' 'h' '' '']
 ['' '' '' '9' '']
 ['' '' '' '' '1']]


In [42]:
print(np.diag([3,4,5]))

[[3 0 0]
 [0 4 0]
 [0 0 5]]


##### linspace
- linear space
- linearly dividing the given interval
- both limits are inclusive
- it will partition the given interval into 50 by default

In [44]:
ln=np.linspace(4,8)
print(ln) # 50 samples

[4.         4.08163265 4.16326531 4.24489796 4.32653061 4.40816327
 4.48979592 4.57142857 4.65306122 4.73469388 4.81632653 4.89795918
 4.97959184 5.06122449 5.14285714 5.2244898  5.30612245 5.3877551
 5.46938776 5.55102041 5.63265306 5.71428571 5.79591837 5.87755102
 5.95918367 6.04081633 6.12244898 6.20408163 6.28571429 6.36734694
 6.44897959 6.53061224 6.6122449  6.69387755 6.7755102  6.85714286
 6.93877551 7.02040816 7.10204082 7.18367347 7.26530612 7.34693878
 7.42857143 7.51020408 7.59183673 7.67346939 7.75510204 7.83673469
 7.91836735 8.        ]


In [45]:
4,5,6,7,8

(4, 5, 6, 7, 8)

In [46]:
5/50

0.1

In [49]:
# restrict the interval
print(np.linspace(1,5,10).reshape(2,5))

[[1.         1.44444444 1.88888889 2.33333333 2.77777778]
 [3.22222222 3.66666667 4.11111111 4.55555556 5.        ]]


#### random()
- is used to generate the random integers 
- random().randint()
- random().randint(,)
- random().randint(,,)
- **generates random samples stars from 0 with shape mentioned**
- random().random()
- random().rand()
- random().randn()

In [58]:
print(np.random.randint(9))

2


In [61]:
print(np.random.randint(40,100)) # random integer

86


In [65]:
print(np.random.randint(40,100,12)) # 12 random values

[55 73 46 65 44 49 93 67 43 82 50 51]


In [68]:
mul=np.random.randint(10,100,12)
mul.reshape(3,4)

array([[23, 33, 77, 79],
       [80, 75, 60, 24],
       [72, 23, 57, 68]])

In [72]:
np.random.random((2,3)) # random floating samples from 0 

array([[0.17288983, 0.98531408, 0.56417936],
       [0.58142345, 0.88518062, 0.82333757]])

In [75]:
np.random.rand(2,4) # 0

array([[0.54805657, 0.18706897, 0.95548292, 0.48114341],
       [0.64120736, 0.01582579, 0.20326643, 0.11178423]])

In [80]:
np.random.randn(3,4) # -ve integers

array([[-0.81288099, -0.12298022, -1.57287225, -0.54014629],
       [-0.48909021, -1.1374224 ,  0.39140514,  0.36742265],
       [-1.31541504,  0.45238047, -0.2228649 ,  1.09770389]])

In [82]:
# numeric values
len(mul)

12

In [83]:
# accessing the array elements

In [84]:
new=mul.reshape(3,4)
print(new)

[[23 33 77 79]
 [80 75 60 24]
 [72 23 57 68]]


In [86]:
new[0] # array entirely depends upon only rows

array([23, 33, 77, 79])

In [88]:
new[1] # 2nd row

array([80, 75, 60, 24])

In [89]:
new[:]

array([[23, 33, 77, 79],
       [80, 75, 60, 24],
       [72, 23, 57, 68]])

In [90]:
new[::]

array([[23, 33, 77, 79],
       [80, 75, 60, 24],
       [72, 23, 57, 68]])

In [91]:
new[::2]

array([[23, 33, 77, 79],
       [72, 23, 57, 68]])

In [92]:
new[::-1]

array([[72, 23, 57, 68],
       [80, 75, 60, 24],
       [23, 33, 77, 79]])

In [93]:
# 2d indexing
new

array([[23, 33, 77, 79],
       [80, 75, 60, 24],
       [72, 23, 57, 68]])

In [94]:
new[0][1]

33

In [95]:
new[:,1:]

array([[33, 77, 79],
       [75, 60, 24],
       [23, 57, 68]])

In [97]:
new[1:,2:] # slicing the rows and cols

array([[60, 24],
       [57, 68]])

In [98]:
rn=np.random.randint(10,100,16).reshape(4,4)
rn

array([[84, 84, 15, 16],
       [43, 53, 81, 58],
       [42, 67, 81, 53],
       [39, 43, 76, 95]])

In [99]:
rn[:2,:2]

array([[84, 84],
       [43, 53]])

In [102]:
rn[::2,::2] # 0 2 4 ;0 2 4
# alternate cols in alternate rows

array([[84, 15],
       [42, 81]])

In [103]:
# fancy indexing
# condition based slicing/indexing

In [104]:
rn

array([[84, 84, 15, 16],
       [43, 53, 81, 58],
       [42, 67, 81, 53],
       [39, 43, 76, 95]])

In [106]:
rn>60 # boolean

array([[ True,  True, False, False],
       [False, False,  True, False],
       [False,  True,  True, False],
       [False, False,  True,  True]])

rn.all() in range(60,90)

In [109]:
rn[rn>60]

array([84, 84, 81, 67, 81, 76, 95])