#### Today Topics
- continue with numpy
- pandas

#### Scientific computation 

In [1]:
import numpy as np

In [9]:
ar=np.random.randint(10,100,25).reshape(5,5)
print(ar)

[[70 62 67 80 59]
 [83 46 59 83 39]
 [31 84 75 32 37]
 [90 97 22 79 80]
 [96 78 13 84 92]]


In [10]:
np.min(ar)

13

In [5]:
np.max(ar)

96

In [6]:
np.sum(ar)

1313

In [7]:
np.mean(ar)

52.52

In [11]:
np.std(ar) # standard deviation

23.955158108432514

#### lagorithms and exponentials

In [12]:
np.log(1)

0.0

In [13]:
np.log(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [14]:
np.log2(2)

1.0

In [15]:
np.log(ar)

array([[4.24849524, 4.12713439, 4.20469262, 4.38202663, 4.07753744],
       [4.41884061, 3.8286414 , 4.07753744, 4.41884061, 3.66356165],
       [3.4339872 , 4.4308168 , 4.31748811, 3.4657359 , 3.61091791],
       [4.49980967, 4.57471098, 3.09104245, 4.36944785, 4.38202663],
       [4.56434819, 4.35670883, 2.56494936, 4.4308168 , 4.52178858]])

In [16]:
np.log([4,5,6,10,12])

array([1.38629436, 1.60943791, 1.79175947, 2.30258509, 2.48490665])

In [18]:
# exponential functions
np.exp(1)

2.718281828459045

In [19]:
np.exp(2)

7.38905609893065

In [20]:
np.exp([5,4,2])

array([148.4131591 ,  54.59815003,   7.3890561 ])

In [21]:
np.exp(ar)
 # the numpy functions are vectorized

array([[2.51543867e+30, 8.43835667e+26, 1.25236317e+29, 5.54062238e+34,
        4.20121040e+25],
       [1.11286375e+36, 9.49611942e+19, 4.20121040e+25, 1.11286375e+36,
        8.65934004e+16],
       [2.90488497e+13, 3.02507732e+36, 3.73324200e+32, 7.89629602e+13,
        1.17191424e+16],
       [1.22040329e+39, 1.33833472e+42, 3.58491285e+09, 2.03828107e+34,
        5.54062238e+34],
       [4.92345829e+41, 7.49841700e+33, 4.42413392e+05, 3.02507732e+36,
        9.01762841e+39]])

#### broad casting
- big change
- applying scalar value on vector
- scalar (1d) it has magnitude
- vector (2d value) magnitude and direction
    - vector (array) has 2 dimensions rows and columns

In [23]:
ar+5# 

array([[ 75,  67,  72,  85,  64],
       [ 88,  51,  64,  88,  44],
       [ 36,  89,  80,  37,  42],
       [ 95, 102,  27,  84,  85],
       [101,  83,  18,  89,  97]])

In [24]:
np.log(ar)

array([[4.24849524, 4.12713439, 4.20469262, 4.38202663, 4.07753744],
       [4.41884061, 3.8286414 , 4.07753744, 4.41884061, 3.66356165],
       [3.4339872 , 4.4308168 , 4.31748811, 3.4657359 , 3.61091791],
       [4.49980967, 4.57471098, 3.09104245, 4.36944785, 4.38202663],
       [4.56434819, 4.35670883, 2.56494936, 4.4308168 , 4.52178858]])

In [25]:
# you can perform all the arithmetic operations on 2 equal size arrays

#### vectorized functions

In [26]:
def greater(a,b):
    if a>b:
        return a
    else:return b
    
    
greater(2,6)

6

In [27]:
greater(10,4)

10

In [28]:
greater([4,5,10],[10,6,3])
# it is just comparing first element

[10, 6, 3]

In [29]:
#[10,6,10]
g=np.vectorize(greater)
g([4,5,10],[10,6,3])

array([10,  6, 10])

##### pandas
- Pandas means PanelData
- one of the most efficient data science modules in data science
- used for data analysis,manipulation and cleaning
    - data analysis
        - analyzing the data means,statistics of the
    - data manipulatin
        - conversion of data from one format to another format
    - data cleaning
        - removal of null data
        
- data can be arranged in 2 formats 
    1. Series
        - sequential data
        - data is arranged either side by side or line by line
    2. DataFrame
        - data is arranged in the form of rows and columns
        - tabular format
- installation process
    - pip install pandas(cmd) in your local machine
    - import the module at work space

In [30]:
import pandas as pd

In [31]:
pd.__version__

'1.0.1'

##### Series
- sequential data items
- pd.Series(data)

In [32]:
# convert str/tuple/list/set/dict into series

In [36]:
st="I am Ruthu"
s=pd.Series(st)
print(s)
s

0    I am Ruthu
dtype: object


0    I am Ruthu
dtype: object

In [38]:
li=[1,2,3,4,10]
li

[1, 2, 3, 4, 10]

In [39]:
pd.Series(li) # conversion of list into series

0     1
1     2
2     3
3     4
4    10
dtype: int64

In [40]:
tp=(3,4,'hi',10,90.45)
pd.Series(tp)

0        3
1        4
2       hi
3       10
4    90.45
dtype: object

In [42]:
S={9,12,34,9,12,56,90} # duplicates(size violation)
pd.Series(S) # SET w

TypeError: 'set' type is unordered

In [43]:
# dictionary into series
# keys as index
dic={'f':23,'s':45,'th':(4,5),'fr':[4,5,6]}
pd.Series(dic)

f            23
s            45
th       (4, 5)
fr    [4, 5, 6]
dtype: object

In [44]:
# range()
# array()

In [45]:
ar=[[3,4,5,2,4],[3,5,3,2,6]] #nested list
pd.Series(ar)

0    [3, 4, 5, 2, 4]
1    [3, 5, 3, 2, 6]
dtype: object

In [46]:
d=np.arange(20)
pd.Series(d)


0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int32

In [47]:
import numpy as np

In [49]:
sr=pd.Series([4,5,6,'hi','hello'],index=[9,8,7,6,5])
sr # adding index

9        4
8        5
7        6
6       hi
5    hello
dtype: object

In [54]:
sd=pd.Series(dic)
sd.index=['R1','R2','R3','R4']
sd

R1           23
R2           45
R3       (4, 5)
R4    [4, 5, 6]
dtype: object

In [52]:
print(dic)

{'f': 23, 's': 45, 'th': (4, 5), 'fr': [4, 5, 6]}


In [56]:
sd[3] # 4th row(default index)

[4, 5, 6]

In [57]:
sd['R4'] # user index

[4, 5, 6]

In [59]:
sd.shape

(4,)

In [60]:
sd.size # no.of items

4

In [62]:
sd

R1           23
R2           45
R3       (4, 5)
R4    [4, 5, 6]
dtype: object

#### DataFrame
- data is aranged in the form of rows&cols
- 2d data structures
- dictionary values into data frame
- keys arranged as columns
- values as rows/index
- pd.DataFrame(iterable)

In [63]:
dic

{'f': 23, 's': 45, 'th': (4, 5), 'fr': [4, 5, 6]}

In [64]:
pd.DataFrame(dic)

ValueError: arrays must all be same length

In [65]:
dc={1:'hi',2:'hello','name':'Ruthu'}
dc

{1: 'hi', 2: 'hello', 'name': 'Ruthu'}

In [67]:
pd.DataFrame(dc,index=[1,2,3]) #

1      2   name
1  hi  hello  Ruthu
2  hi  hello  Ruthu
3  hi  hello  Ruthu

In [69]:
pd.DataFrame(dic,index=[1,2])

ValueError: could not broadcast input array from shape (3) into shape (2)

In [70]:
dic

{'f': 23, 's': 45, 'th': (4, 5), 'fr': [4, 5, 6]}

In [71]:
d={'a':[1,2,3],'b':[6,7,8],'c':[9,0,4]} # I haven't passed index
df=pd.DataFrame(d)
df

a  b  c
0  1  6  9
1  2  7  0
2  3  8  4

In [72]:
d={'a':[1,2,3],'b':[6,7,8],'c':[9,0,4]} # I haven't passed index
df=pd.DataFrame(d,index=['Row1','Row2','Row3'])
df

a  b  c
Row1  1  6  9
Row2  2  7  0
Row3  3  8  4

In [73]:
# create the following data frame
Int    float      str
xx     x.x        'xxx'
...     ....       '...'




# five lines of dataframe

SyntaxError: invalid syntax (<ipython-input-73-97ae9e721173>, line 2)

In [74]:
r={'Int':[1,2,3,4,5],'float':[1.1,2.2,3.3,4.4,5.5],'str':['we','are','atudying','in','gvpce']}
rf=pd.DataFrame(r)
rf


Int  float       str
0    1    1.1        we
1    2    2.2       are
2    3    3.3  atudying
3    4    4.4        in
4    5    5.5     gvpce

In [75]:
dl={'int':[1,2,3,4,5],'float':[6.6,7.4,8.8,9.5,1.5],'str':['g','e','t','h','i']}
dlc=pd.DataFrame(dl,index=['Row1','Row2','Row3','Row4','Row5'])
dlc


int  float str
Row1    1    6.6   g
Row2    2    7.4   e
Row3    3    8.8   t
Row4    4    9.5   h
Row5    5    1.5   i

In [77]:
dlc.columns # list of column names

Index(['int', 'float', 'str'], dtype='object')

In [78]:
dlc.index # index names

Index(['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], dtype='object')

In [80]:
dlc.shape # (rows,cols)

(5, 3)

In [83]:
dlc.size

15

In [84]:
# perticular column data
dlc[3] # depends on columns

KeyError: 3

In [85]:
dlc['float'] # float col-->rows 

Row1    6.6
Row2    7.4
Row3    8.8
Row4    9.5
Row5    1.5
Name: float, dtype: float64

In [86]:
df

a  b  c
Row1  1  6  9
Row2  2  7  0
Row3  3  8  4

In [87]:
df['c']

Row1    9
Row2    0
Row3    4
Name: c, dtype: int64

In [88]:
# multiple cols

In [89]:
df[['a','c']] # nested list

a  c
Row1  1  9
Row2  2  0
Row3  3  4

In [93]:
df['c']['Row3'] # 2d index[col][row]

4

In [94]:
df

a  b  c
Row1  1  6  9
Row2  2  7  0
Row3  3  8  4

In [95]:
# two equal size dfs
# merge,join,concat-->take similar cols but with diff rows

In [99]:
df.any() # colmns values giving by default

a    True
b    True
c    True
dtype: bool

In [100]:
dlc.any(axis='columns') # 

Row1    True
Row2    True
Row3    True
Row4    True
Row5    True
dtype: bool

In [98]:
dlc.all() # 

int      True
float    True
str      True
dtype: bool

In [101]:
dlc.append(df)

int  float  str    a    b    c
Row1  1.0    6.6    g  NaN  NaN  NaN
Row2  2.0    7.4    e  NaN  NaN  NaN
Row3  3.0    8.8    t  NaN  NaN  NaN
Row4  4.0    9.5    h  NaN  NaN  NaN
Row5  5.0    1.5    i  NaN  NaN  NaN
Row1  NaN    NaN  NaN  1.0  6.0  9.0
Row2  NaN    NaN  NaN  2.0  7.0  0.0
Row3  NaN    NaN  NaN  3.0  8.0  4.0

In [102]:
dlc.append(df,ignore_index=True)

int  float  str    a    b    c
0  1.0    6.6    g  NaN  NaN  NaN
1  2.0    7.4    e  NaN  NaN  NaN
2  3.0    8.8    t  NaN  NaN  NaN
3  4.0    9.5    h  NaN  NaN  NaN
4  5.0    1.5    i  NaN  NaN  NaN
5  NaN    NaN  NaN  1.0  6.0  9.0
6  NaN    NaN  NaN  2.0  7.0  0.0
7  NaN    NaN  NaN  3.0  8.0  4.0

In [104]:
df

a  b  c
Row1  1  6  9
Row2  2  7  0
Row3  3  8  4

In [110]:
first=pd.DataFrame({'a':[90,85,68,50],'b':[90,85,89,50],
      'c':[90,85,70,50]})
second=pd.DataFrame({'a':[90,85,98,50],'b':[90,85,9,50],
      'c':[90,85,90,50]})
first.merge(second) # merging on perticular colmns

a   b   c
0  90  90  90
1  85  85  85
2  50  50  50

In [113]:
first.join(second)

ValueError: columns overlap but no suffix specified: Index(['a', 'b', 'c'], dtype='object')

In [115]:
# join adding exta colums to the rows
third=pd.DataFrame({'p':[90,85,98,50],'q':[90,85,9,50],
      'r':[90,85,90,50]})
first.join(third)

a   b   c   p   q   r
0  90  90  90  90  90  90
1  85  85  85  85  85  85
2  68  89  70  98   9  90
3  50  50  50  50  50  50

In [116]:
# concatenation means
# different rows get added under existed columns
one=pd.DataFrame({'me':'deepu','clg':'gvpce'},index=[1,2])
two=pd.DataFrame({'name':'kumar','clg':'gvpce2'},index=[1,2])
print(pd.concat([one,two]))
# best

      me     clg   name
1  deepu   gvpce    NaN
2  deepu   gvpce    NaN
1    NaN  gvpce2  kumar
2    NaN  gvpce2  kumar


In [118]:
pd.concat([[first,third]]) # because...?

TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid

In [119]:
first

a   b   c
0  90  90  90
1  85  85  85
2  68  89  70
3  50  50  50

In [120]:
second

a   b   c
0  90  90  90
1  85  85  85
2  98   9  90
3  50  50  50

In [121]:
third

p   q   r
0  90  90  90
1  85  85  85
2  98   9  90
3  50  50  50

In [123]:
new=pd.concat([second,third])
#second contains:a,b,c;third contains:p,q,r;
#NaN:Not a Number:Null data
new

a     b     c     p     q     r
0  90.0  90.0  90.0   NaN   NaN   NaN
1  85.0  85.0  85.0   NaN   NaN   NaN
2  98.0   9.0  90.0   NaN   NaN   NaN
3  50.0  50.0  50.0   NaN   NaN   NaN
0   NaN   NaN   NaN  90.0  90.0  90.0
1   NaN   NaN   NaN  85.0  85.0  85.0
2   NaN   NaN   NaN  98.0   9.0  90.0
3   NaN   NaN   NaN  50.0  50.0  50.0

In [125]:
new.isna() # checking for null characters

a      b      c      p      q      r
0  False  False  False   True   True   True
1  False  False  False   True   True   True
2  False  False  False   True   True   True
3  False  False  False   True   True   True
0   True   True   True  False  False  False
1   True   True   True  False  False  False
2   True   True   True  False  False  False
3   True   True   True  False  False  False

In [126]:
first=pd.DataFrame({'a':[90,85,68,50],'b':[90,85,89,50],
      'c':[90,85,70,50]})
second=pd.DataFrame({'a':[90,85,98,50],'b':[90,85,9,50],
      'c':[90,85,90,50]})
first.merge(second,on='b') # merging on perticular colmns
# a_x,c_x->a,c belongs to first,a_y,c_y-->second df

a_x   b  c_x  a_y  c_y
0   90  90   90   90   90
1   85  85   85   85   85
2   50  50   50   50   50

In [127]:
df1 = pd.DataFrame({"A": [1,2,3,4],"B": [10,20,30,40],"C": [100,101,102,103],"D": [0,0,0,0]},index=[0, 1, 2, 3])
df2=pd.DataFrame({"hello":[11,12,13,14],"hii":[15,16,17,18],"ram":[100,200,300,400],"vikas":[201,202,203,204]},index=[500,501,601,701])
a=[df1,df2]
print(pd.concat(a))


       A     B      C    D  hello   hii    ram  vikas
0    1.0  10.0  100.0  0.0    NaN   NaN    NaN    NaN
1    2.0  20.0  101.0  0.0    NaN   NaN    NaN    NaN
2    3.0  30.0  102.0  0.0    NaN   NaN    NaN    NaN
3    4.0  40.0  103.0  0.0    NaN   NaN    NaN    NaN
500  NaN   NaN    NaN  NaN   11.0  15.0  100.0  201.0
501  NaN   NaN    NaN  NaN   12.0  16.0  200.0  202.0
601  NaN   NaN    NaN  NaN   13.0  17.0  300.0  203.0
701  NaN   NaN    NaN  NaN   14.0  18.0  400.0  204.0


In [129]:
first = pd.DataFrame({'a':[1,2,3,4],'b':[1,2,3,5],'c':[1,2,3,6],'d':[1,2,3,6]},index=['p1','p2','p3','p4'])
second = pd.DataFrame({'a':[2,3,4,5],'b':[1,2,4,5],'c':[2,3,4,7],'d':[2,3,4,8]},index=['n1','n2','n3','n4'])
first.merge(second,on='c')

a_x  b_x  c  d_x  a_y  b_y  d_y
0    2    2  2    2    2    1    2
1    3    3  3    3    3    2    3

#### working with .csv file

In [131]:
df1 = pd.DataFrame({"A": [1,2,3,4],"B": [10,20,30,40],"C": [100,101,102,103],"D": [0,0,0,0]})
df2=pd.DataFrame({"A":[1,2,3,4],"B":[10,20,30,18],"C":[100,200,300,400],"D":[0,0,203,204]})
a=[df1,df2]
print(pd.concat(a))
df1.merge(df2,on="B")


   A   B    C    D
0  1  10  100    0
1  2  20  101    0
2  3  30  102    0
3  4  40  103    0
0  1  10  100    0
1  2  20  200    0
2  3  30  300  203
3  4  18  400  204


A_x   B  C_x  D_x  A_y  C_y  D_y
0    1  10  100    0    1  100    0
1    2  20  101    0    2  200    0
2    3  30  102    0    3  300  203

#### working .csv file
- comma separated values

In [132]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_np_version_under1p

In [133]:
df=pd.read_csv('marks.csv')
df

Name   PE  DA  DS   PS  MPS   SS
0     Jaswanth   96  99  86   99   87   87
1       Harini   97  88  87   91   93   95
2        Amala   99  99  97   93   88   97
3     Geethika   88  96  97   90   90   98
4   Prathyusha   97  89  93   94   94   87
5      Nandini   90  97  87   98   92   86
6     Srikanya   95  85  85  100   90   97
7      Rithika  100  87  91   89   96   99
8        Deepu   94  97  87   85   99   85
9       Renuka   95  86  94   87   91   95
10         Joy   88  86  97   94   90   87
11      Elisha   90  91  93   97   87   91
12     Fathima   98  91  99   98   91  100
13        Rani   87  99  96   93   94   93
14     Lakshmi   95  99  98   89   95   91

In [134]:
spc=pd.read_csv('marks.csv',usecols=['DA','PS'])
spc # specific column data

DA   PS
0   99   99
1   88   91
2   99   93
3   96   90
4   89   94
5   97   98
6   85  100
7   87   89
8   97   85
9   86   87
10  86   94
11  91   97
12  91   98
13  99   93
14  99   89

In [135]:
new=pd.read_csv('marks.csv',header=None)
new # removal of header

0    1   2   3    4    5    6
0         Name   PE  DA  DS   PS  MPS   SS
1     Jaswanth   96  99  86   99   87   87
2       Harini   97  88  87   91   93   95
3        Amala   99  99  97   93   88   97
4     Geethika   88  96  97   90   90   98
5   Prathyusha   97  89  93   94   94   87
6      Nandini   90  97  87   98   92   86
7     Srikanya   95  85  85  100   90   97
8      Rithika  100  87  91   89   96   99
9        Deepu   94  97  87   85   99   85
10      Renuka   95  86  94   87   91   95
11         Joy   88  86  97   94   90   87
12      Elisha   90  91  93   97   87   91
13     Fathima   98  91  99   98   91  100
14        Rani   87  99  96   93   94   93
15     Lakshmi   95  99  98   89   95   91

In [136]:
df

Name   PE  DA  DS   PS  MPS   SS
0     Jaswanth   96  99  86   99   87   87
1       Harini   97  88  87   91   93   95
2        Amala   99  99  97   93   88   97
3     Geethika   88  96  97   90   90   98
4   Prathyusha   97  89  93   94   94   87
5      Nandini   90  97  87   98   92   86
6     Srikanya   95  85  85  100   90   97
7      Rithika  100  87  91   89   96   99
8        Deepu   94  97  87   85   99   85
9       Renuka   95  86  94   87   91   95
10         Joy   88  86  97   94   90   87
11      Elisha   90  91  93   97   87   91
12     Fathima   98  91  99   98   91  100
13        Rani   87  99  96   93   94   93
14     Lakshmi   95  99  98   89   95   91

In [137]:
df['MPS']

0     87
1     93
2     88
3     90
4     94
5     92
6     90
7     96
8     99
9     91
10    90
11    87
12    91
13    94
14    95
Name: MPS, dtype: int64

In [138]:
df.columns

Index(['Name', 'PE', 'DA', 'DS', 'PS', 'MPS', 'SS'], dtype='object')

In [139]:
df.MPS # column as attribute

0     87
1     93
2     88
3     90
4     94
5     92
6     90
7     96
8     99
9     91
10    90
11    87
12    91
13    94
14    95
Name: MPS, dtype: int64

In [141]:
df.PS.value_counts() 
# counting the frequency of each value under the column

94     2
93     2
89     2
98     2
91     1
90     1
87     1
85     1
100    1
99     1
97     1
Name: PS, dtype: int64

In [142]:
df.DA.sum() # summation of col DA

1389

In [143]:
df.describe() # statistics of data set

PE         DA         DS          PS        MPS          SS
count   15.000000  15.000000  15.000000   15.000000  15.000000   15.000000
mean    93.933333  92.600000  92.466667   93.133333  91.800000   92.533333
std      4.267262   5.539469   4.926121    4.611580   3.405877    5.180550
min     87.000000  85.000000  85.000000   85.000000  87.000000   85.000000
25%     90.000000  87.500000  87.000000   89.500000  90.000000   87.000000
50%     95.000000  91.000000  93.000000   93.000000  91.000000   93.000000
75%     97.000000  98.000000  97.000000   97.500000  94.000000   97.000000
max    100.000000  99.000000  99.000000  100.000000  99.000000  100.000000

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    15 non-null     object
 1   PE      15 non-null     int64 
 2   DA      15 non-null     int64 
 3   DS      15 non-null     int64 
 4   PS      15 non-null     int64 
 5   MPS     15 non-null     int64 
 6   SS      15 non-null     int64 
dtypes: int64(6), object(1)
memory usage: 844.0+ bytes


In [146]:
df.index=[num for num in range(1,16)]
df #updating the index value

Name   PE  DA  DS   PS  MPS   SS
1     Jaswanth   96  99  86   99   87   87
2       Harini   97  88  87   91   93   95
3        Amala   99  99  97   93   88   97
4     Geethika   88  96  97   90   90   98
5   Prathyusha   97  89  93   94   94   87
6      Nandini   90  97  87   98   92   86
7     Srikanya   95  85  85  100   90   97
8      Rithika  100  87  91   89   96   99
9        Deepu   94  97  87   85   99   85
10      Renuka   95  86  94   87   91   95
11         Joy   88  86  97   94   90   87
12      Elisha   90  91  93   97   87   91
13     Fathima   98  91  99   98   91  100
14        Rani   87  99  96   93   94   93
15     Lakshmi   95  99  98   89   95   91

In [147]:
df.DS.min()

85

In [150]:
df.sample() # random sample

Name  PE  DA  DS  PS  MPS  SS
5  Prathyusha  97  89  93  94   94  87

In [154]:
df.sample(3) # n random samples

Name   PE  DA  DS  PS  MPS  SS
12    Elisha   90  91  93  97   87  91
8    Rithika  100  87  91  89   96  99
1   Jaswanth   96  99  86  99   87  87

In [156]:
#df.DS.sort()

AttributeError: 'Series' object has no attribute 'sort'

In [158]:
df.head() # first 5 samples by default

Name  PE  DA  DS  PS  MPS  SS
1    Jaswanth  96  99  86  99   87  87
2      Harini  97  88  87  91   93  95
3       Amala  99  99  97  93   88  97
4    Geethika  88  96  97  90   90  98
5  Prathyusha  97  89  93  94   94  87

In [159]:
df.head(2)

Name  PE  DA  DS  PS  MPS  SS
1  Jaswanth  96  99  86  99   87  87
2    Harini  97  88  87  91   93  95

In [161]:
df.tail() # by default 5 last samples

Name  PE  DA  DS  PS  MPS   SS
11      Joy  88  86  97  94   90   87
12   Elisha  90  91  93  97   87   91
13  Fathima  98  91  99  98   91  100
14     Rani  87  99  96  93   94   93
15  Lakshmi  95  99  98  89   95   91

In [162]:
df.tail(3)

Name  PE  DA  DS  PS  MPS   SS
13  Fathima  98  91  99  98   91  100
14     Rani  87  99  96  93   94   93
15  Lakshmi  95  99  98  89   95   91

In [168]:
df[::2] # index-->rows

Name  PE  DA  DS   PS  MPS   SS
1     Jaswanth  96  99  86   99   87   87
3        Amala  99  99  97   93   88   97
5   Prathyusha  97  89  93   94   94   87
7     Srikanya  95  85  85  100   90   97
9        Deepu  94  97  87   85   99   85
11         Joy  88  86  97   94   90   87
13     Fathima  98  91  99   98   91  100
15     Lakshmi  95  99  98   89   95   91

In [169]:
df.isnull()

Name     PE     DA     DS     PS    MPS     SS
1   False  False  False  False  False  False  False
2   False  False  False  False  False  False  False
3   False  False  False  False  False  False  False
4   False  False  False  False  False  False  False
5   False  False  False  False  False  False  False
6   False  False  False  False  False  False  False
7   False  False  False  False  False  False  False
8   False  False  False  False  False  False  False
9   False  False  False  False  False  False  False
10  False  False  False  False  False  False  False
11  False  False  False  False  False  False  False
12  False  False  False  False  False  False  False
13  False  False  False  False  False  False  False
14  False  False  False  False  False  False  False
15  False  False  False  False  False  False  False

In [171]:
marks_df=pd.read_csv('marks.csv')
marks_df

Name     PE     DA     DS    PS    MPS     SS
0     Jaswanth   98.0   91.0   97.0  86.0   95.0   96.0
1       Harini   91.0   92.0   96.0   NaN   89.0   99.0
2        Amala   87.0   99.0   87.0  87.0   91.0  100.0
3     Geethika   98.0   85.0   98.0  95.0   94.0    NaN
4   Prathyusha   90.0  100.0   92.0  90.0  100.0   91.0
5      Nandini   99.0   89.0    NaN  94.0   97.0   93.0
6     Srikanya    NaN    NaN   90.0  86.0   97.0   89.0
7      Rithika  100.0   90.0   94.0  95.0   93.0   87.0
8        Deepu  100.0   87.0   90.0  92.0    NaN   91.0
9       Renuka  100.0    NaN   95.0  85.0   95.0   86.0
10         Joy   98.0  100.0   87.0  98.0   87.0   99.0
11      Elisha   89.0   97.0  100.0  96.0   91.0   86.0
12     Fathima   85.0   94.0    NaN  86.0   88.0    NaN
13        Rani  100.0   92.0   88.0   NaN    NaN   92.0
14     Lakshmi   96.0   91.0   85.0  96.0   95.0   92.0

In [172]:
marks_df.isna()

Name     PE     DA     DS     PS    MPS     SS
0   False  False  False  False  False  False  False
1   False  False  False  False   True  False  False
2   False  False  False  False  False  False  False
3   False  False  False  False  False  False   True
4   False  False  False  False  False  False  False
5   False  False  False   True  False  False  False
6   False   True   True  False  False  False  False
7   False  False  False  False  False  False  False
8   False  False  False  False  False   True  False
9   False  False   True  False  False  False  False
10  False  False  False  False  False  False  False
11  False  False  False  False  False  False  False
12  False  False  False   True  False  False   True
13  False  False  False  False   True   True  False
14  False  False  False  False  False  False  False

In [173]:
marks_df.dropna()

Name     PE     DA     DS    PS    MPS     SS
0     Jaswanth   98.0   91.0   97.0  86.0   95.0   96.0
2        Amala   87.0   99.0   87.0  87.0   91.0  100.0
4   Prathyusha   90.0  100.0   92.0  90.0  100.0   91.0
7      Rithika  100.0   90.0   94.0  95.0   93.0   87.0
10         Joy   98.0  100.0   87.0  98.0   87.0   99.0
11      Elisha   89.0   97.0  100.0  96.0   91.0   86.0
14     Lakshmi   96.0   91.0   85.0  96.0   95.0   92.0

In [174]:
updated=marks_df.dropna()
updated

Name     PE     DA     DS    PS    MPS     SS
0     Jaswanth   98.0   91.0   97.0  86.0   95.0   96.0
2        Amala   87.0   99.0   87.0  87.0   91.0  100.0
4   Prathyusha   90.0  100.0   92.0  90.0  100.0   91.0
7      Rithika  100.0   90.0   94.0  95.0   93.0   87.0
10         Joy   98.0  100.0   87.0  98.0   87.0   99.0
11      Elisha   89.0   97.0  100.0  96.0   91.0   86.0
14     Lakshmi   96.0   91.0   85.0  96.0   95.0   92.0

In [176]:
# you can add col
updated['Total']=100

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [177]:
updated

Name     PE     DA     DS    PS    MPS     SS  Total
0     Jaswanth   98.0   91.0   97.0  86.0   95.0   96.0    100
2        Amala   87.0   99.0   87.0  87.0   91.0  100.0    100
4   Prathyusha   90.0  100.0   92.0  90.0  100.0   91.0    100
7      Rithika  100.0   90.0   94.0  95.0   93.0   87.0    100
10         Joy   98.0  100.0   87.0  98.0   87.0   99.0    100
11      Elisha   89.0   97.0  100.0  96.0   91.0   86.0    100
14     Lakshmi   96.0   91.0   85.0  96.0   95.0   92.0    100